// Real subcontractor authorization signatures for a bundle trade.
//
// Generates the per-trade authorization PDF from the same prefill the GC can copy to the
// clipboard, stores it next to the permit's other files, and hands it to the existing
// SignWell pipeline (signwell-send → signature_requests → signwell-webhook). Nothing here
// marks a trade signed: only the HMAC-verified document_completed event does that.

import { supabase } from "@/integrations/supabase/client";
import { generateAgreementPdf } from "@/lib/private-provider-forms";
import { sendForSignature, type SignatureRequest } from "@/lib/signature-requests";
import { buildBundlePrefill, type Bundle, type BundleTrade } from "@/lib/bundle";
import type { PermitRow } from "@/lib/permits-api";

const BUCKET = "permit-files";

/** Stable per-trade document name — the key the ledger row is matched back on. */
export function tradeDocumentName(trade: Pick<BundleTrade, "label">): string {
  return `${trade.label} — Subcontractor Authorization`;
}

function tradeAuthorizationSections(prefill: ReturnType<typeof buildBundlePrefill>, sub: string) {
  return [
    {
      heading: "1. Trade and Scope",
      body: `${sub} ("Subcontractor") is engaged to perform the ${prefill.trade} scope of work at ${prefill.project_address}, under the permit administered by ${prefill.gc_name} (licence ${prefill.gc_license}) with ${prefill.municipality || "the local building department"}.`,
    },
    {
      heading: "2. Authorization to Include on the Permit Application",
      body: "Subcontractor authorizes the general contractor and its permit agent to list Subcontractor on the permit application and supporting documents for this project, and to submit Subcontractor's licence and insurance certificates to the building department in support of that application.",
    },
    {
      heading: "3. Licence and Insurance",
      body: "Subcontractor confirms that its state licence and insurance coverage are current as of the date signed, and will notify the general contractor in writing if either lapses or is materially changed while the permit remains open.",
    },
    {
      heading: "4. Responsibility for the Work",
      body: "Subcontractor remains solely responsible for the means, methods, and code compliance of its own scope, including scheduling and passing the inspections applicable to that scope. This authorization does not transfer responsibility for the work to the general contractor or its permit agent.",
    },
    {
      heading: "5. Effect",
      body: "This authorization applies to the permit identified above and to any revision or resubmittal of it. It does not create a construction contract and does not alter the commercial terms agreed separately between the parties.",
    },
  ];
}

export async function sendTradeForSignature(
  row: PermitRow,
  trade: BundleTrade,
  bundle: Bundle,
): Promise<SignatureRequest> {
  const sub = trade.sub_snapshot;
  const email = sub?.email?.trim();
  if (!sub || !email) {
    throw new Error(`No email on file for the ${trade.label} sub.`);
  }

  const prefill = buildBundlePrefill(row, trade, bundle);
  const bytes = await generateAgreementPdf({
    title: "Subcontractor Authorization",
    subtitle: `${prefill.trade} — ${prefill.project_address}`,
    intro:
      "This authorization is prepared by Cleard on behalf of the general contractor of record and is signed electronically through SignWell.",
    facts: [
      { label: "Project Address", value: prefill.project_address },
      { label: "Municipality", value: prefill.municipality || "—" },
      { label: "Permit Type", value: prefill.permit_type || "—" },
      { label: "Permit Number", value: prefill.permit_number || "— pending —" },
      { label: "Trade", value: prefill.trade },
      { label: "Subcontractor", value: sub.company },
      { label: "Subcontractor Licence", value: sub.license || "—" },
      { label: "General Contractor", value: `${prefill.gc_name} · ${prefill.gc_license}` },
      {
        label: "Permit Agent Contact",
        value: `${prefill.poc_name} · ${prefill.poc_email} · ${prefill.poc_phone}`,
      },
    ],
    sections: tradeAuthorizationSections(prefill, sub.company),
    signatureLabel: `${sub.company} — Authorized Signature`,
    footer: "Generated by Cleard. Executed electronically via SignWell.",
  });

  const path = `bundle-signatures/${row.id}/${trade.key}-${Date.now()}.pdf`;
  const { error: upErr } = await supabase.storage
    .from(BUCKET)
    .upload(path, new Blob([bytes as BlobPart], { type: "application/pdf" }), {
      contentType: "application/pdf",
      upsert: true,
    });
  if (upErr) throw new Error(`Could not store the authorization PDF: ${upErr.message}`);

  return sendForSignature({
    permitId: row.id,
    documentName: tradeDocumentName(trade),
    documentPath: path,
    recipientEmail: email,
    recipientName: sub.contact || sub.company,
    recipientRole: "Subcontractor",
    subject: `Signature required — ${prefill.trade} authorization, ${prefill.project_address}`,
    message: `${prefill.gc_name} has listed ${sub.company} on the ${prefill.trade} scope for ${prefill.project_address}. Please review and sign the authorization so the permit can be submitted.`,
    // The sub is external to the portal, so SignWell emails them the signing link.
    sendEmail: true,
  });
}

/**
 * Provider truth for a trade. A ledger row on its own only means "sent" — SignWell has to
 * confirm completion before a trade counts as signed.
 */
export function tradeSignatureState(
  req: SignatureRequest | undefined,
): "pending" | "sent" | "signed" {
  if (!req) return "pending";
  if (req.status === "signed" && req.statusSource === "provider_confirmed") return "signed";
  return "sent";
}
