/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectGuidesRouteImport } from './routes/project-guides'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as MyPermitsRouteImport } from './routes/my-permits'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LpoaSigningRouteImport } from './routes/lpoa-signing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as GcPortalRouteImport } from './routes/gc-portal'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as FeeCalculatorRouteImport } from './routes/fee-calculator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuildingDeptLoginsRouteImport } from './routes/building-dept-logins'
import { Route as AskVictoriaRouteImport } from './routes/ask-victoria'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as SubIntakeTokenRouteImport } from './routes/sub-intake.$token'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as PortalRequestSubInsuranceRouteImport } from './routes/portal.request-sub-insurance'
import { Route as PortalRequestCoiRouteImport } from './routes/portal.request-coi'
import { Route as PortalProjectsRouteImport } from './routes/portal.projects'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalPermitsRouteImport } from './routes/portal.permits'
import { Route as PortalPermitFeesRouteImport } from './routes/portal.permit-fees'
import { Route as PortalNotaryQueueRouteImport } from './routes/portal.notary-queue'
import { Route as PortalNewPermitRouteImport } from './routes/portal.new-permit'
import { Route as PortalInspectionsRouteImport } from './routes/portal.inspections'
import { Route as PortalEquipmentSpecsRouteImport } from './routes/portal.equipment-specs'
import { Route as PortalBuildingDeptRouteImport } from './routes/portal.building-dept'
import { Route as PermitCardIdRouteImport } from './routes/permit-card.$id'
import { Route as FormsSubcontractorIntakeRouteImport } from './routes/forms.subcontractor-intake'
import { Route as FormsPermitIntakeRouteImport } from './routes/forms.permit-intake'
import { Route as FormsPaymentAuthorizationRouteImport } from './routes/forms.payment-authorization'
import { Route as BuildingDeptLoginsSubmitRouteImport } from './routes/building-dept-logins.submit'
import { Route as AdminContractorsRouteImport } from './routes/admin_.contractors'
import { Route as AdminHubspotSimulateRouteImport } from './routes/admin.hubspot-simulate'
import { Route as AdminGcClientsRouteImport } from './routes/admin.gc-clients'
import { Route as AdminBuildersRouteImport } from './routes/admin.builders'
import { Route as PortalSubcontractorsIndexRouteImport } from './routes/portal.subcontractors.index'
import { Route as PortalPermitsIndexRouteImport } from './routes/portal.permits.index'
import { Route as PortalGuidesIndexRouteImport } from './routes/portal.guides.index'
import { Route as PortalSubcontractorsNewRouteImport } from './routes/portal.subcontractors.new'
import { Route as PortalProjectsIdRouteImport } from './routes/portal.projects.$id'
import { Route as PortalPermitsNewRouteImport } from './routes/portal.permits.new'
import { Route as PortalPermitsIdRouteImport } from './routes/portal.permits.$id'
import { Route as PortalGuidesSlugRouteImport } from './routes/portal.guides.$slug'
import { Route as ApiPublicSeedTeamRouteImport } from './routes/api/public/seed-team'
import { Route as ApiPublicHubspotDealWebhookRouteImport } from './routes/api/public/hubspot.deal-webhook'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectGuidesRoute = ProjectGuidesRouteImport.update({
  id: '/project-guides',
  path: '/project-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPermitsRoute = MyPermitsRouteImport.update({
  id: '/my-permits',
  path: '/my-permits',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LpoaSigningRoute = LpoaSigningRouteImport.update({
  id: '/lpoa-signing',
  path: '/lpoa-signing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const GcPortalRoute = GcPortalRouteImport.update({
  id: '/gc-portal',
  path: '/gc-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeCalculatorRoute = FeeCalculatorRouteImport.update({
  id: '/fee-calculator',
  path: '/fee-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingDeptLoginsRoute = BuildingDeptLoginsRouteImport.update({
  id: '/building-dept-logins',
  path: '/building-dept-logins',
  getParentRoute: () => rootRouteImport,
} as any)
const AskVictoriaRoute = AskVictoriaRouteImport.update({
  id: '/ask-victoria',
  path: '/ask-victoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const SubIntakeTokenRoute = SubIntakeTokenRouteImport.update({
  id: '/sub-intake/$token',
  path: '/sub-intake/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const PortalRequestSubInsuranceRoute =
  PortalRequestSubInsuranceRouteImport.update({
    id: '/request-sub-insurance',
    path: '/request-sub-insurance',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalRequestCoiRoute = PortalRequestCoiRouteImport.update({
  id: '/request-coi',
  path: '/request-coi',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProjectsRoute = PortalProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPermitsRoute = PortalPermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPermitFeesRoute = PortalPermitFeesRouteImport.update({
  id: '/permit-fees',
  path: '/permit-fees',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNotaryQueueRoute = PortalNotaryQueueRouteImport.update({
  id: '/notary-queue',
  path: '/notary-queue',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNewPermitRoute = PortalNewPermitRouteImport.update({
  id: '/new-permit',
  path: '/new-permit',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInspectionsRoute = PortalInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEquipmentSpecsRoute = PortalEquipmentSpecsRouteImport.update({
  id: '/equipment-specs',
  path: '/equipment-specs',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBuildingDeptRoute = PortalBuildingDeptRouteImport.update({
  id: '/building-dept',
  path: '/building-dept',
  getParentRoute: () => PortalRoute,
} as any)
const PermitCardIdRoute = PermitCardIdRouteImport.update({
  id: '/permit-card/$id',
  path: '/permit-card/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsSubcontractorIntakeRoute =
  FormsSubcontractorIntakeRouteImport.update({
    id: '/subcontractor-intake',
    path: '/subcontractor-intake',
    getParentRoute: () => FormsRoute,
  } as any)
const FormsPermitIntakeRoute = FormsPermitIntakeRouteImport.update({
  id: '/permit-intake',
  path: '/permit-intake',
  getParentRoute: () => FormsRoute,
} as any)
const FormsPaymentAuthorizationRoute =
  FormsPaymentAuthorizationRouteImport.update({
    id: '/payment-authorization',
    path: '/payment-authorization',
    getParentRoute: () => FormsRoute,
  } as any)
const BuildingDeptLoginsSubmitRoute =
  BuildingDeptLoginsSubmitRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => BuildingDeptLoginsRoute,
  } as any)
const AdminContractorsRoute = AdminContractorsRouteImport.update({
  id: '/admin_/contractors',
  path: '/admin/contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHubspotSimulateRoute = AdminHubspotSimulateRouteImport.update({
  id: '/hubspot-simulate',
  path: '/hubspot-simulate',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGcClientsRoute = AdminGcClientsRouteImport.update({
  id: '/gc-clients',
  path: '/gc-clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuildersRoute = AdminBuildersRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => AdminRoute,
} as any)
const PortalSubcontractorsIndexRoute =
  PortalSubcontractorsIndexRouteImport.update({
    id: '/subcontractors/',
    path: '/subcontractors/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalPermitsIndexRoute = PortalPermitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalPermitsRoute,
} as any)
const PortalGuidesIndexRoute = PortalGuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSubcontractorsNewRoute = PortalSubcontractorsNewRouteImport.update({
  id: '/subcontractors/new',
  path: '/subcontractors/new',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProjectsIdRoute = PortalProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalProjectsRoute,
} as any)
const PortalPermitsNewRoute = PortalPermitsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PortalPermitsRoute,
} as any)
const PortalPermitsIdRoute = PortalPermitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalPermitsRoute,
} as any)
const PortalGuidesSlugRoute = PortalGuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => PortalRoute,
} as any)
const ApiPublicSeedTeamRoute = ApiPublicSeedTeamRouteImport.update({
  id: '/api/public/seed-team',
  path: '/api/public/seed-team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHubspotDealWebhookRoute =
  ApiPublicHubspotDealWebhookRouteImport.update({
    id: '/api/public/hubspot/deal-webhook',
    path: '/api/public/hubspot/deal-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask-victoria': typeof AskVictoriaRoute
  '/building-dept-logins': typeof BuildingDeptLoginsRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/fee-calculator': typeof FeeCalculatorRoute
  '/forms': typeof FormsRouteWithChildren
  '/gc-portal': typeof GcPortalRoute
  '/insurance': typeof InsuranceRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/lpoa-signing': typeof LpoaSigningRoute
  '/messages': typeof MessagesRoute
  '/my-permits': typeof MyPermitsRoute
  '/portal': typeof PortalRouteWithChildren
  '/process': typeof ProcessRoute
  '/profile': typeof ProfileRoute
  '/project-guides': typeof ProjectGuidesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/services': typeof ServicesRoute
  '/admin/builders': typeof AdminBuildersRoute
  '/admin/gc-clients': typeof AdminGcClientsRoute
  '/admin/hubspot-simulate': typeof AdminHubspotSimulateRoute
  '/admin/contractors': typeof AdminContractorsRoute
  '/building-dept-logins/submit': typeof BuildingDeptLoginsSubmitRoute
  '/forms/payment-authorization': typeof FormsPaymentAuthorizationRoute
  '/forms/permit-intake': typeof FormsPermitIntakeRoute
  '/forms/subcontractor-intake': typeof FormsSubcontractorIntakeRoute
  '/permit-card/$id': typeof PermitCardIdRoute
  '/portal/building-dept': typeof PortalBuildingDeptRoute
  '/portal/equipment-specs': typeof PortalEquipmentSpecsRoute
  '/portal/inspections': typeof PortalInspectionsRoute
  '/portal/new-permit': typeof PortalNewPermitRoute
  '/portal/notary-queue': typeof PortalNotaryQueueRoute
  '/portal/permit-fees': typeof PortalPermitFeesRoute
  '/portal/permits': typeof PortalPermitsRouteWithChildren
  '/portal/profile': typeof PortalProfileRoute
  '/portal/projects': typeof PortalProjectsRouteWithChildren
  '/portal/request-coi': typeof PortalRequestCoiRoute
  '/portal/request-sub-insurance': typeof PortalRequestSubInsuranceRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/sub-intake/$token': typeof SubIntakeTokenRoute
  '/portal/': typeof PortalIndexRoute
  '/api/public/seed-team': typeof ApiPublicSeedTeamRoute
  '/portal/guides/$slug': typeof PortalGuidesSlugRoute
  '/portal/permits/$id': typeof PortalPermitsIdRoute
  '/portal/permits/new': typeof PortalPermitsNewRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
  '/portal/subcontractors/new': typeof PortalSubcontractorsNewRoute
  '/portal/guides/': typeof PortalGuidesIndexRoute
  '/portal/permits/': typeof PortalPermitsIndexRoute
  '/portal/subcontractors/': typeof PortalSubcontractorsIndexRoute
  '/api/public/hubspot/deal-webhook': typeof ApiPublicHubspotDealWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask-victoria': typeof AskVictoriaRoute
  '/building-dept-logins': typeof BuildingDeptLoginsRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/fee-calculator': typeof FeeCalculatorRoute
  '/forms': typeof FormsRouteWithChildren
  '/gc-portal': typeof GcPortalRoute
  '/insurance': typeof InsuranceRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/lpoa-signing': typeof LpoaSigningRoute
  '/messages': typeof MessagesRoute
  '/my-permits': typeof MyPermitsRoute
  '/process': typeof ProcessRoute
  '/profile': typeof ProfileRoute
  '/project-guides': typeof ProjectGuidesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/services': typeof ServicesRoute
  '/admin/builders': typeof AdminBuildersRoute
  '/admin/gc-clients': typeof AdminGcClientsRoute
  '/admin/hubspot-simulate': typeof AdminHubspotSimulateRoute
  '/admin/contractors': typeof AdminContractorsRoute
  '/building-dept-logins/submit': typeof BuildingDeptLoginsSubmitRoute
  '/forms/payment-authorization': typeof FormsPaymentAuthorizationRoute
  '/forms/permit-intake': typeof FormsPermitIntakeRoute
  '/forms/subcontractor-intake': typeof FormsSubcontractorIntakeRoute
  '/permit-card/$id': typeof PermitCardIdRoute
  '/portal/building-dept': typeof PortalBuildingDeptRoute
  '/portal/equipment-specs': typeof PortalEquipmentSpecsRoute
  '/portal/inspections': typeof PortalInspectionsRoute
  '/portal/new-permit': typeof PortalNewPermitRoute
  '/portal/notary-queue': typeof PortalNotaryQueueRoute
  '/portal/permit-fees': typeof PortalPermitFeesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/projects': typeof PortalProjectsRouteWithChildren
  '/portal/request-coi': typeof PortalRequestCoiRoute
  '/portal/request-sub-insurance': typeof PortalRequestSubInsuranceRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/sub-intake/$token': typeof SubIntakeTokenRoute
  '/portal': typeof PortalIndexRoute
  '/api/public/seed-team': typeof ApiPublicSeedTeamRoute
  '/portal/guides/$slug': typeof PortalGuidesSlugRoute
  '/portal/permits/$id': typeof PortalPermitsIdRoute
  '/portal/permits/new': typeof PortalPermitsNewRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
  '/portal/subcontractors/new': typeof PortalSubcontractorsNewRoute
  '/portal/guides': typeof PortalGuidesIndexRoute
  '/portal/permits': typeof PortalPermitsIndexRoute
  '/portal/subcontractors': typeof PortalSubcontractorsIndexRoute
  '/api/public/hubspot/deal-webhook': typeof ApiPublicHubspotDealWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask-victoria': typeof AskVictoriaRoute
  '/building-dept-logins': typeof BuildingDeptLoginsRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/fee-calculator': typeof FeeCalculatorRoute
  '/forms': typeof FormsRouteWithChildren
  '/gc-portal': typeof GcPortalRoute
  '/insurance': typeof InsuranceRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/lpoa-signing': typeof LpoaSigningRoute
  '/messages': typeof MessagesRoute
  '/my-permits': typeof MyPermitsRoute
  '/portal': typeof PortalRouteWithChildren
  '/process': typeof ProcessRoute
  '/profile': typeof ProfileRoute
  '/project-guides': typeof ProjectGuidesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/services': typeof ServicesRoute
  '/admin/builders': typeof AdminBuildersRoute
  '/admin/gc-clients': typeof AdminGcClientsRoute
  '/admin/hubspot-simulate': typeof AdminHubspotSimulateRoute
  '/admin_/contractors': typeof AdminContractorsRoute
  '/building-dept-logins/submit': typeof BuildingDeptLoginsSubmitRoute
  '/forms/payment-authorization': typeof FormsPaymentAuthorizationRoute
  '/forms/permit-intake': typeof FormsPermitIntakeRoute
  '/forms/subcontractor-intake': typeof FormsSubcontractorIntakeRoute
  '/permit-card/$id': typeof PermitCardIdRoute
  '/portal/building-dept': typeof PortalBuildingDeptRoute
  '/portal/equipment-specs': typeof PortalEquipmentSpecsRoute
  '/portal/inspections': typeof PortalInspectionsRoute
  '/portal/new-permit': typeof PortalNewPermitRoute
  '/portal/notary-queue': typeof PortalNotaryQueueRoute
  '/portal/permit-fees': typeof PortalPermitFeesRoute
  '/portal/permits': typeof PortalPermitsRouteWithChildren
  '/portal/profile': typeof PortalProfileRoute
  '/portal/projects': typeof PortalProjectsRouteWithChildren
  '/portal/request-coi': typeof PortalRequestCoiRoute
  '/portal/request-sub-insurance': typeof PortalRequestSubInsuranceRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/sub-intake/$token': typeof SubIntakeTokenRoute
  '/portal/': typeof PortalIndexRoute
  '/api/public/seed-team': typeof ApiPublicSeedTeamRoute
  '/portal/guides/$slug': typeof PortalGuidesSlugRoute
  '/portal/permits/$id': typeof PortalPermitsIdRoute
  '/portal/permits/new': typeof PortalPermitsNewRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
  '/portal/subcontractors/new': typeof PortalSubcontractorsNewRoute
  '/portal/guides/': typeof PortalGuidesIndexRoute
  '/portal/permits/': typeof PortalPermitsIndexRoute
  '/portal/subcontractors/': typeof PortalSubcontractorsIndexRoute
  '/api/public/hubspot/deal-webhook': typeof ApiPublicHubspotDealWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ask-victoria'
    | '/building-dept-logins'
    | '/contact'
    | '/dashboard'
    | '/fee-calculator'
    | '/forms'
    | '/gc-portal'
    | '/insurance'
    | '/invoices'
    | '/login'
    | '/lpoa-signing'
    | '/messages'
    | '/my-permits'
    | '/portal'
    | '/process'
    | '/profile'
    | '/project-guides'
    | '/projects'
    | '/services'
    | '/admin/builders'
    | '/admin/gc-clients'
    | '/admin/hubspot-simulate'
    | '/admin/contractors'
    | '/building-dept-logins/submit'
    | '/forms/payment-authorization'
    | '/forms/permit-intake'
    | '/forms/subcontractor-intake'
    | '/permit-card/$id'
    | '/portal/building-dept'
    | '/portal/equipment-specs'
    | '/portal/inspections'
    | '/portal/new-permit'
    | '/portal/notary-queue'
    | '/portal/permit-fees'
    | '/portal/permits'
    | '/portal/profile'
    | '/portal/projects'
    | '/portal/request-coi'
    | '/portal/request-sub-insurance'
    | '/projects/$id'
    | '/projects/new'
    | '/sub-intake/$token'
    | '/portal/'
    | '/api/public/seed-team'
    | '/portal/guides/$slug'
    | '/portal/permits/$id'
    | '/portal/permits/new'
    | '/portal/projects/$id'
    | '/portal/subcontractors/new'
    | '/portal/guides/'
    | '/portal/permits/'
    | '/portal/subcontractors/'
    | '/api/public/hubspot/deal-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ask-victoria'
    | '/building-dept-logins'
    | '/contact'
    | '/dashboard'
    | '/fee-calculator'
    | '/forms'
    | '/gc-portal'
    | '/insurance'
    | '/invoices'
    | '/login'
    | '/lpoa-signing'
    | '/messages'
    | '/my-permits'
    | '/process'
    | '/profile'
    | '/project-guides'
    | '/projects'
    | '/services'
    | '/admin/builders'
    | '/admin/gc-clients'
    | '/admin/hubspot-simulate'
    | '/admin/contractors'
    | '/building-dept-logins/submit'
    | '/forms/payment-authorization'
    | '/forms/permit-intake'
    | '/forms/subcontractor-intake'
    | '/permit-card/$id'
    | '/portal/building-dept'
    | '/portal/equipment-specs'
    | '/portal/inspections'
    | '/portal/new-permit'
    | '/portal/notary-queue'
    | '/portal/permit-fees'
    | '/portal/profile'
    | '/portal/projects'
    | '/portal/request-coi'
    | '/portal/request-sub-insurance'
    | '/projects/$id'
    | '/projects/new'
    | '/sub-intake/$token'
    | '/portal'
    | '/api/public/seed-team'
    | '/portal/guides/$slug'
    | '/portal/permits/$id'
    | '/portal/permits/new'
    | '/portal/projects/$id'
    | '/portal/subcontractors/new'
    | '/portal/guides'
    | '/portal/permits'
    | '/portal/subcontractors'
    | '/api/public/hubspot/deal-webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ask-victoria'
    | '/building-dept-logins'
    | '/contact'
    | '/dashboard'
    | '/fee-calculator'
    | '/forms'
    | '/gc-portal'
    | '/insurance'
    | '/invoices'
    | '/login'
    | '/lpoa-signing'
    | '/messages'
    | '/my-permits'
    | '/portal'
    | '/process'
    | '/profile'
    | '/project-guides'
    | '/projects'
    | '/services'
    | '/admin/builders'
    | '/admin/gc-clients'
    | '/admin/hubspot-simulate'
    | '/admin_/contractors'
    | '/building-dept-logins/submit'
    | '/forms/payment-authorization'
    | '/forms/permit-intake'
    | '/forms/subcontractor-intake'
    | '/permit-card/$id'
    | '/portal/building-dept'
    | '/portal/equipment-specs'
    | '/portal/inspections'
    | '/portal/new-permit'
    | '/portal/notary-queue'
    | '/portal/permit-fees'
    | '/portal/permits'
    | '/portal/profile'
    | '/portal/projects'
    | '/portal/request-coi'
    | '/portal/request-sub-insurance'
    | '/projects/$id'
    | '/projects/new'
    | '/sub-intake/$token'
    | '/portal/'
    | '/api/public/seed-team'
    | '/portal/guides/$slug'
    | '/portal/permits/$id'
    | '/portal/permits/new'
    | '/portal/projects/$id'
    | '/portal/subcontractors/new'
    | '/portal/guides/'
    | '/portal/permits/'
    | '/portal/subcontractors/'
    | '/api/public/hubspot/deal-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AskVictoriaRoute: typeof AskVictoriaRoute
  BuildingDeptLoginsRoute: typeof BuildingDeptLoginsRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FeeCalculatorRoute: typeof FeeCalculatorRoute
  FormsRoute: typeof FormsRouteWithChildren
  GcPortalRoute: typeof GcPortalRoute
  InsuranceRoute: typeof InsuranceRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  LpoaSigningRoute: typeof LpoaSigningRoute
  MessagesRoute: typeof MessagesRoute
  MyPermitsRoute: typeof MyPermitsRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProcessRoute: typeof ProcessRoute
  ProfileRoute: typeof ProfileRoute
  ProjectGuidesRoute: typeof ProjectGuidesRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  AdminContractorsRoute: typeof AdminContractorsRoute
  PermitCardIdRoute: typeof PermitCardIdRoute
  SubIntakeTokenRoute: typeof SubIntakeTokenRoute
  ApiPublicSeedTeamRoute: typeof ApiPublicSeedTeamRoute
  ApiPublicHubspotDealWebhookRoute: typeof ApiPublicHubspotDealWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-guides': {
      id: '/project-guides'
      path: '/project-guides'
      fullPath: '/project-guides'
      preLoaderRoute: typeof ProjectGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-permits': {
      id: '/my-permits'
      path: '/my-permits'
      fullPath: '/my-permits'
      preLoaderRoute: typeof MyPermitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpoa-signing': {
      id: '/lpoa-signing'
      path: '/lpoa-signing'
      fullPath: '/lpoa-signing'
      preLoaderRoute: typeof LpoaSigningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gc-portal': {
      id: '/gc-portal'
      path: '/gc-portal'
      fullPath: '/gc-portal'
      preLoaderRoute: typeof GcPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-calculator': {
      id: '/fee-calculator'
      path: '/fee-calculator'
      fullPath: '/fee-calculator'
      preLoaderRoute: typeof FeeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building-dept-logins': {
      id: '/building-dept-logins'
      path: '/building-dept-logins'
      fullPath: '/building-dept-logins'
      preLoaderRoute: typeof BuildingDeptLoginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-victoria': {
      id: '/ask-victoria'
      path: '/ask-victoria'
      fullPath: '/ask-victoria'
      preLoaderRoute: typeof AskVictoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/sub-intake/$token': {
      id: '/sub-intake/$token'
      path: '/sub-intake/$token'
      fullPath: '/sub-intake/$token'
      preLoaderRoute: typeof SubIntakeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/portal/request-sub-insurance': {
      id: '/portal/request-sub-insurance'
      path: '/request-sub-insurance'
      fullPath: '/portal/request-sub-insurance'
      preLoaderRoute: typeof PortalRequestSubInsuranceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/request-coi': {
      id: '/portal/request-coi'
      path: '/request-coi'
      fullPath: '/portal/request-coi'
      preLoaderRoute: typeof PortalRequestCoiRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/projects': {
      id: '/portal/projects'
      path: '/projects'
      fullPath: '/portal/projects'
      preLoaderRoute: typeof PortalProjectsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/permits': {
      id: '/portal/permits'
      path: '/permits'
      fullPath: '/portal/permits'
      preLoaderRoute: typeof PortalPermitsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/permit-fees': {
      id: '/portal/permit-fees'
      path: '/permit-fees'
      fullPath: '/portal/permit-fees'
      preLoaderRoute: typeof PortalPermitFeesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/notary-queue': {
      id: '/portal/notary-queue'
      path: '/notary-queue'
      fullPath: '/portal/notary-queue'
      preLoaderRoute: typeof PortalNotaryQueueRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/new-permit': {
      id: '/portal/new-permit'
      path: '/new-permit'
      fullPath: '/portal/new-permit'
      preLoaderRoute: typeof PortalNewPermitRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/inspections': {
      id: '/portal/inspections'
      path: '/inspections'
      fullPath: '/portal/inspections'
      preLoaderRoute: typeof PortalInspectionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/equipment-specs': {
      id: '/portal/equipment-specs'
      path: '/equipment-specs'
      fullPath: '/portal/equipment-specs'
      preLoaderRoute: typeof PortalEquipmentSpecsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/building-dept': {
      id: '/portal/building-dept'
      path: '/building-dept'
      fullPath: '/portal/building-dept'
      preLoaderRoute: typeof PortalBuildingDeptRouteImport
      parentRoute: typeof PortalRoute
    }
    '/permit-card/$id': {
      id: '/permit-card/$id'
      path: '/permit-card/$id'
      fullPath: '/permit-card/$id'
      preLoaderRoute: typeof PermitCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/subcontractor-intake': {
      id: '/forms/subcontractor-intake'
      path: '/subcontractor-intake'
      fullPath: '/forms/subcontractor-intake'
      preLoaderRoute: typeof FormsSubcontractorIntakeRouteImport
      parentRoute: typeof FormsRoute
    }
    '/forms/permit-intake': {
      id: '/forms/permit-intake'
      path: '/permit-intake'
      fullPath: '/forms/permit-intake'
      preLoaderRoute: typeof FormsPermitIntakeRouteImport
      parentRoute: typeof FormsRoute
    }
    '/forms/payment-authorization': {
      id: '/forms/payment-authorization'
      path: '/payment-authorization'
      fullPath: '/forms/payment-authorization'
      preLoaderRoute: typeof FormsPaymentAuthorizationRouteImport
      parentRoute: typeof FormsRoute
    }
    '/building-dept-logins/submit': {
      id: '/building-dept-logins/submit'
      path: '/submit'
      fullPath: '/building-dept-logins/submit'
      preLoaderRoute: typeof BuildingDeptLoginsSubmitRouteImport
      parentRoute: typeof BuildingDeptLoginsRoute
    }
    '/admin_/contractors': {
      id: '/admin_/contractors'
      path: '/admin/contractors'
      fullPath: '/admin/contractors'
      preLoaderRoute: typeof AdminContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hubspot-simulate': {
      id: '/admin/hubspot-simulate'
      path: '/hubspot-simulate'
      fullPath: '/admin/hubspot-simulate'
      preLoaderRoute: typeof AdminHubspotSimulateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gc-clients': {
      id: '/admin/gc-clients'
      path: '/gc-clients'
      fullPath: '/admin/gc-clients'
      preLoaderRoute: typeof AdminGcClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/builders': {
      id: '/admin/builders'
      path: '/builders'
      fullPath: '/admin/builders'
      preLoaderRoute: typeof AdminBuildersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/subcontractors/': {
      id: '/portal/subcontractors/'
      path: '/subcontractors'
      fullPath: '/portal/subcontractors/'
      preLoaderRoute: typeof PortalSubcontractorsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/permits/': {
      id: '/portal/permits/'
      path: '/'
      fullPath: '/portal/permits/'
      preLoaderRoute: typeof PortalPermitsIndexRouteImport
      parentRoute: typeof PortalPermitsRoute
    }
    '/portal/guides/': {
      id: '/portal/guides/'
      path: '/guides'
      fullPath: '/portal/guides/'
      preLoaderRoute: typeof PortalGuidesIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/subcontractors/new': {
      id: '/portal/subcontractors/new'
      path: '/subcontractors/new'
      fullPath: '/portal/subcontractors/new'
      preLoaderRoute: typeof PortalSubcontractorsNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/projects/$id': {
      id: '/portal/projects/$id'
      path: '/$id'
      fullPath: '/portal/projects/$id'
      preLoaderRoute: typeof PortalProjectsIdRouteImport
      parentRoute: typeof PortalProjectsRoute
    }
    '/portal/permits/new': {
      id: '/portal/permits/new'
      path: '/new'
      fullPath: '/portal/permits/new'
      preLoaderRoute: typeof PortalPermitsNewRouteImport
      parentRoute: typeof PortalPermitsRoute
    }
    '/portal/permits/$id': {
      id: '/portal/permits/$id'
      path: '/$id'
      fullPath: '/portal/permits/$id'
      preLoaderRoute: typeof PortalPermitsIdRouteImport
      parentRoute: typeof PortalPermitsRoute
    }
    '/portal/guides/$slug': {
      id: '/portal/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/portal/guides/$slug'
      preLoaderRoute: typeof PortalGuidesSlugRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/public/seed-team': {
      id: '/api/public/seed-team'
      path: '/api/public/seed-team'
      fullPath: '/api/public/seed-team'
      preLoaderRoute: typeof ApiPublicSeedTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hubspot/deal-webhook': {
      id: '/api/public/hubspot/deal-webhook'
      path: '/api/public/hubspot/deal-webhook'
      fullPath: '/api/public/hubspot/deal-webhook'
      preLoaderRoute: typeof ApiPublicHubspotDealWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBuildersRoute: typeof AdminBuildersRoute
  AdminGcClientsRoute: typeof AdminGcClientsRoute
  AdminHubspotSimulateRoute: typeof AdminHubspotSimulateRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBuildersRoute: AdminBuildersRoute,
  AdminGcClientsRoute: AdminGcClientsRoute,
  AdminHubspotSimulateRoute: AdminHubspotSimulateRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BuildingDeptLoginsRouteChildren {
  BuildingDeptLoginsSubmitRoute: typeof BuildingDeptLoginsSubmitRoute
}

const BuildingDeptLoginsRouteChildren: BuildingDeptLoginsRouteChildren = {
  BuildingDeptLoginsSubmitRoute: BuildingDeptLoginsSubmitRoute,
}

const BuildingDeptLoginsRouteWithChildren =
  BuildingDeptLoginsRoute._addFileChildren(BuildingDeptLoginsRouteChildren)

interface FormsRouteChildren {
  FormsPaymentAuthorizationRoute: typeof FormsPaymentAuthorizationRoute
  FormsPermitIntakeRoute: typeof FormsPermitIntakeRoute
  FormsSubcontractorIntakeRoute: typeof FormsSubcontractorIntakeRoute
}

const FormsRouteChildren: FormsRouteChildren = {
  FormsPaymentAuthorizationRoute: FormsPaymentAuthorizationRoute,
  FormsPermitIntakeRoute: FormsPermitIntakeRoute,
  FormsSubcontractorIntakeRoute: FormsSubcontractorIntakeRoute,
}

const FormsRouteWithChildren = FormsRoute._addFileChildren(FormsRouteChildren)

interface PortalPermitsRouteChildren {
  PortalPermitsIdRoute: typeof PortalPermitsIdRoute
  PortalPermitsNewRoute: typeof PortalPermitsNewRoute
  PortalPermitsIndexRoute: typeof PortalPermitsIndexRoute
}

const PortalPermitsRouteChildren: PortalPermitsRouteChildren = {
  PortalPermitsIdRoute: PortalPermitsIdRoute,
  PortalPermitsNewRoute: PortalPermitsNewRoute,
  PortalPermitsIndexRoute: PortalPermitsIndexRoute,
}

const PortalPermitsRouteWithChildren = PortalPermitsRoute._addFileChildren(
  PortalPermitsRouteChildren,
)

interface PortalProjectsRouteChildren {
  PortalProjectsIdRoute: typeof PortalProjectsIdRoute
}

const PortalProjectsRouteChildren: PortalProjectsRouteChildren = {
  PortalProjectsIdRoute: PortalProjectsIdRoute,
}

const PortalProjectsRouteWithChildren = PortalProjectsRoute._addFileChildren(
  PortalProjectsRouteChildren,
)

interface PortalRouteChildren {
  PortalBuildingDeptRoute: typeof PortalBuildingDeptRoute
  PortalEquipmentSpecsRoute: typeof PortalEquipmentSpecsRoute
  PortalInspectionsRoute: typeof PortalInspectionsRoute
  PortalNewPermitRoute: typeof PortalNewPermitRoute
  PortalNotaryQueueRoute: typeof PortalNotaryQueueRoute
  PortalPermitFeesRoute: typeof PortalPermitFeesRoute
  PortalPermitsRoute: typeof PortalPermitsRouteWithChildren
  PortalProfileRoute: typeof PortalProfileRoute
  PortalProjectsRoute: typeof PortalProjectsRouteWithChildren
  PortalRequestCoiRoute: typeof PortalRequestCoiRoute
  PortalRequestSubInsuranceRoute: typeof PortalRequestSubInsuranceRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalGuidesSlugRoute: typeof PortalGuidesSlugRoute
  PortalSubcontractorsNewRoute: typeof PortalSubcontractorsNewRoute
  PortalGuidesIndexRoute: typeof PortalGuidesIndexRoute
  PortalSubcontractorsIndexRoute: typeof PortalSubcontractorsIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBuildingDeptRoute: PortalBuildingDeptRoute,
  PortalEquipmentSpecsRoute: PortalEquipmentSpecsRoute,
  PortalInspectionsRoute: PortalInspectionsRoute,
  PortalNewPermitRoute: PortalNewPermitRoute,
  PortalNotaryQueueRoute: PortalNotaryQueueRoute,
  PortalPermitFeesRoute: PortalPermitFeesRoute,
  PortalPermitsRoute: PortalPermitsRouteWithChildren,
  PortalProfileRoute: PortalProfileRoute,
  PortalProjectsRoute: PortalProjectsRouteWithChildren,
  PortalRequestCoiRoute: PortalRequestCoiRoute,
  PortalRequestSubInsuranceRoute: PortalRequestSubInsuranceRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalGuidesSlugRoute: PortalGuidesSlugRoute,
  PortalSubcontractorsNewRoute: PortalSubcontractorsNewRoute,
  PortalGuidesIndexRoute: PortalGuidesIndexRoute,
  PortalSubcontractorsIndexRoute: PortalSubcontractorsIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AskVictoriaRoute: AskVictoriaRoute,
  BuildingDeptLoginsRoute: BuildingDeptLoginsRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FeeCalculatorRoute: FeeCalculatorRoute,
  FormsRoute: FormsRouteWithChildren,
  GcPortalRoute: GcPortalRoute,
  InsuranceRoute: InsuranceRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  LpoaSigningRoute: LpoaSigningRoute,
  MessagesRoute: MessagesRoute,
  MyPermitsRoute: MyPermitsRoute,
  PortalRoute: PortalRouteWithChildren,
  ProcessRoute: ProcessRoute,
  ProfileRoute: ProfileRoute,
  ProjectGuidesRoute: ProjectGuidesRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ServicesRoute: ServicesRoute,
  AdminContractorsRoute: AdminContractorsRoute,
  PermitCardIdRoute: PermitCardIdRoute,
  SubIntakeTokenRoute: SubIntakeTokenRoute,
  ApiPublicSeedTeamRoute: ApiPublicSeedTeamRoute,
  ApiPublicHubspotDealWebhookRoute: ApiPublicHubspotDealWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
