/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectGuidesRouteImport } from './routes/project-guides'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as MyPermitsRouteImport } from './routes/my-permits'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LpoaSigningRouteImport } from './routes/lpoa-signing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as FeeCalculatorRouteImport } from './routes/fee-calculator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuildingDeptLoginsRouteImport } from './routes/building-dept-logins'
import { Route as AskVictoriaRouteImport } from './routes/ask-victoria'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as PortalProjectsRouteImport } from './routes/portal.projects'
import { Route as PortalNewPermitRouteImport } from './routes/portal.new-permit'
import { Route as PortalInspectionsRouteImport } from './routes/portal.inspections'
import { Route as FormsSubcontractorIntakeRouteImport } from './routes/forms.subcontractor-intake'
import { Route as FormsPermitIntakeRouteImport } from './routes/forms.permit-intake'
import { Route as FormsPaymentAuthorizationRouteImport } from './routes/forms.payment-authorization'
import { Route as BuildingDeptLoginsSubmitRouteImport } from './routes/building-dept-logins.submit'
import { Route as AdminBuildersRouteImport } from './routes/admin.builders'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectGuidesRoute = ProjectGuidesRouteImport.update({
  id: '/project-guides',
  path: '/project-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPermitsRoute = MyPermitsRouteImport.update({
  id: '/my-permits',
  path: '/my-permits',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LpoaSigningRoute = LpoaSigningRouteImport.update({
  id: '/lpoa-signing',
  path: '/lpoa-signing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeCalculatorRoute = FeeCalculatorRouteImport.update({
  id: '/fee-calculator',
  path: '/fee-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingDeptLoginsRoute = BuildingDeptLoginsRouteImport.update({
  id: '/building-dept-logins',
  path: '/building-dept-logins',
  getParentRoute: () => rootRouteImport,
} as any)
const AskVictoriaRoute = AskVictoriaRouteImport.update({
  id: '/ask-victoria',
  path: '/ask-victoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const PortalProjectsRoute = PortalProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNewPermitRoute = PortalNewPermitRouteImport.update({
  id: '/new-permit',
  path: '/new-permit',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInspectionsRoute = PortalInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => PortalRoute,
} as any)
const FormsSubcontractorIntakeRoute =
  FormsSubcontractorIntakeRouteImport.update({
    id: '/subcontractor-intake',
    path: '/subcontractor-intake',
    getParentRoute: () => FormsRoute,
  } as any)
const FormsPermitIntakeRoute = FormsPermitIntakeRouteImport.update({
  id: '/permit-intake',
  path: '/permit-intake',
  getParentRoute: () => FormsRoute,
} as any)
const FormsPaymentAuthorizationRoute =
  FormsPaymentAuthorizationRouteImport.update({
    id: '/payment-authorization',
    path: '/payment-authorization',
    getParentRoute: () => FormsRoute,
  } as any)
const BuildingDeptLoginsSubmitRoute =
  BuildingDeptLoginsSubmitRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => BuildingDeptLoginsRoute,
  } as any)
const AdminBuildersRoute = AdminBuildersRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask-victoria': typeof AskVictoriaRoute
  '/building-dept-logins': typeof BuildingDeptLoginsRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/fee-calculator': typeof FeeCalculatorRoute
  '/forms': typeof FormsRouteWithChildren
  '/insurance': typeof InsuranceRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/lpoa-signing': typeof LpoaSigningRoute
  '/messages': typeof MessagesRoute
  '/my-permits': typeof MyPermitsRoute
  '/portal': typeof PortalRouteWithChildren
  '/process': typeof ProcessRoute
  '/profile': typeof ProfileRoute
  '/project-guides': typeof ProjectGuidesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/services': typeof ServicesRoute
  '/admin/builders': typeof AdminBuildersRoute
  '/building-dept-logins/submit': typeof BuildingDeptLoginsSubmitRoute
  '/forms/payment-authorization': typeof FormsPaymentAuthorizationRoute
  '/forms/permit-intake': typeof FormsPermitIntakeRoute
  '/forms/subcontractor-intake': typeof FormsSubcontractorIntakeRoute
  '/portal/inspections': typeof PortalInspectionsRoute
  '/portal/new-permit': typeof PortalNewPermitRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask-victoria': typeof AskVictoriaRoute
  '/building-dept-logins': typeof BuildingDeptLoginsRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/fee-calculator': typeof FeeCalculatorRoute
  '/forms': typeof FormsRouteWithChildren
  '/insurance': typeof InsuranceRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/lpoa-signing': typeof LpoaSigningRoute
  '/messages': typeof MessagesRoute
  '/my-permits': typeof MyPermitsRoute
  '/process': typeof ProcessRoute
  '/profile': typeof ProfileRoute
  '/project-guides': typeof ProjectGuidesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/services': typeof ServicesRoute
  '/admin/builders': typeof AdminBuildersRoute
  '/building-dept-logins/submit': typeof BuildingDeptLoginsSubmitRoute
  '/forms/payment-authorization': typeof FormsPaymentAuthorizationRoute
  '/forms/permit-intake': typeof FormsPermitIntakeRoute
  '/forms/subcontractor-intake': typeof FormsSubcontractorIntakeRoute
  '/portal/inspections': typeof PortalInspectionsRoute
  '/portal/new-permit': typeof PortalNewPermitRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask-victoria': typeof AskVictoriaRoute
  '/building-dept-logins': typeof BuildingDeptLoginsRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/fee-calculator': typeof FeeCalculatorRoute
  '/forms': typeof FormsRouteWithChildren
  '/insurance': typeof InsuranceRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/lpoa-signing': typeof LpoaSigningRoute
  '/messages': typeof MessagesRoute
  '/my-permits': typeof MyPermitsRoute
  '/portal': typeof PortalRouteWithChildren
  '/process': typeof ProcessRoute
  '/profile': typeof ProfileRoute
  '/project-guides': typeof ProjectGuidesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/services': typeof ServicesRoute
  '/admin/builders': typeof AdminBuildersRoute
  '/building-dept-logins/submit': typeof BuildingDeptLoginsSubmitRoute
  '/forms/payment-authorization': typeof FormsPaymentAuthorizationRoute
  '/forms/permit-intake': typeof FormsPermitIntakeRoute
  '/forms/subcontractor-intake': typeof FormsSubcontractorIntakeRoute
  '/portal/inspections': typeof PortalInspectionsRoute
  '/portal/new-permit': typeof PortalNewPermitRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ask-victoria'
    | '/building-dept-logins'
    | '/contact'
    | '/dashboard'
    | '/fee-calculator'
    | '/forms'
    | '/insurance'
    | '/invoices'
    | '/login'
    | '/lpoa-signing'
    | '/messages'
    | '/my-permits'
    | '/portal'
    | '/process'
    | '/profile'
    | '/project-guides'
    | '/projects'
    | '/services'
    | '/admin/builders'
    | '/building-dept-logins/submit'
    | '/forms/payment-authorization'
    | '/forms/permit-intake'
    | '/forms/subcontractor-intake'
    | '/portal/inspections'
    | '/portal/new-permit'
    | '/portal/projects'
    | '/projects/$id'
    | '/projects/new'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ask-victoria'
    | '/building-dept-logins'
    | '/contact'
    | '/dashboard'
    | '/fee-calculator'
    | '/forms'
    | '/insurance'
    | '/invoices'
    | '/login'
    | '/lpoa-signing'
    | '/messages'
    | '/my-permits'
    | '/process'
    | '/profile'
    | '/project-guides'
    | '/projects'
    | '/services'
    | '/admin/builders'
    | '/building-dept-logins/submit'
    | '/forms/payment-authorization'
    | '/forms/permit-intake'
    | '/forms/subcontractor-intake'
    | '/portal/inspections'
    | '/portal/new-permit'
    | '/portal/projects'
    | '/projects/$id'
    | '/projects/new'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ask-victoria'
    | '/building-dept-logins'
    | '/contact'
    | '/dashboard'
    | '/fee-calculator'
    | '/forms'
    | '/insurance'
    | '/invoices'
    | '/login'
    | '/lpoa-signing'
    | '/messages'
    | '/my-permits'
    | '/portal'
    | '/process'
    | '/profile'
    | '/project-guides'
    | '/projects'
    | '/services'
    | '/admin/builders'
    | '/building-dept-logins/submit'
    | '/forms/payment-authorization'
    | '/forms/permit-intake'
    | '/forms/subcontractor-intake'
    | '/portal/inspections'
    | '/portal/new-permit'
    | '/portal/projects'
    | '/projects/$id'
    | '/projects/new'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AskVictoriaRoute: typeof AskVictoriaRoute
  BuildingDeptLoginsRoute: typeof BuildingDeptLoginsRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FeeCalculatorRoute: typeof FeeCalculatorRoute
  FormsRoute: typeof FormsRouteWithChildren
  InsuranceRoute: typeof InsuranceRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  LpoaSigningRoute: typeof LpoaSigningRoute
  MessagesRoute: typeof MessagesRoute
  MyPermitsRoute: typeof MyPermitsRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProcessRoute: typeof ProcessRoute
  ProfileRoute: typeof ProfileRoute
  ProjectGuidesRoute: typeof ProjectGuidesRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-guides': {
      id: '/project-guides'
      path: '/project-guides'
      fullPath: '/project-guides'
      preLoaderRoute: typeof ProjectGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-permits': {
      id: '/my-permits'
      path: '/my-permits'
      fullPath: '/my-permits'
      preLoaderRoute: typeof MyPermitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpoa-signing': {
      id: '/lpoa-signing'
      path: '/lpoa-signing'
      fullPath: '/lpoa-signing'
      preLoaderRoute: typeof LpoaSigningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-calculator': {
      id: '/fee-calculator'
      path: '/fee-calculator'
      fullPath: '/fee-calculator'
      preLoaderRoute: typeof FeeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building-dept-logins': {
      id: '/building-dept-logins'
      path: '/building-dept-logins'
      fullPath: '/building-dept-logins'
      preLoaderRoute: typeof BuildingDeptLoginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-victoria': {
      id: '/ask-victoria'
      path: '/ask-victoria'
      fullPath: '/ask-victoria'
      preLoaderRoute: typeof AskVictoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/portal/projects': {
      id: '/portal/projects'
      path: '/projects'
      fullPath: '/portal/projects'
      preLoaderRoute: typeof PortalProjectsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/new-permit': {
      id: '/portal/new-permit'
      path: '/new-permit'
      fullPath: '/portal/new-permit'
      preLoaderRoute: typeof PortalNewPermitRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/inspections': {
      id: '/portal/inspections'
      path: '/inspections'
      fullPath: '/portal/inspections'
      preLoaderRoute: typeof PortalInspectionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/forms/subcontractor-intake': {
      id: '/forms/subcontractor-intake'
      path: '/subcontractor-intake'
      fullPath: '/forms/subcontractor-intake'
      preLoaderRoute: typeof FormsSubcontractorIntakeRouteImport
      parentRoute: typeof FormsRoute
    }
    '/forms/permit-intake': {
      id: '/forms/permit-intake'
      path: '/permit-intake'
      fullPath: '/forms/permit-intake'
      preLoaderRoute: typeof FormsPermitIntakeRouteImport
      parentRoute: typeof FormsRoute
    }
    '/forms/payment-authorization': {
      id: '/forms/payment-authorization'
      path: '/payment-authorization'
      fullPath: '/forms/payment-authorization'
      preLoaderRoute: typeof FormsPaymentAuthorizationRouteImport
      parentRoute: typeof FormsRoute
    }
    '/building-dept-logins/submit': {
      id: '/building-dept-logins/submit'
      path: '/submit'
      fullPath: '/building-dept-logins/submit'
      preLoaderRoute: typeof BuildingDeptLoginsSubmitRouteImport
      parentRoute: typeof BuildingDeptLoginsRoute
    }
    '/admin/builders': {
      id: '/admin/builders'
      path: '/builders'
      fullPath: '/admin/builders'
      preLoaderRoute: typeof AdminBuildersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBuildersRoute: typeof AdminBuildersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBuildersRoute: AdminBuildersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BuildingDeptLoginsRouteChildren {
  BuildingDeptLoginsSubmitRoute: typeof BuildingDeptLoginsSubmitRoute
}

const BuildingDeptLoginsRouteChildren: BuildingDeptLoginsRouteChildren = {
  BuildingDeptLoginsSubmitRoute: BuildingDeptLoginsSubmitRoute,
}

const BuildingDeptLoginsRouteWithChildren =
  BuildingDeptLoginsRoute._addFileChildren(BuildingDeptLoginsRouteChildren)

interface FormsRouteChildren {
  FormsPaymentAuthorizationRoute: typeof FormsPaymentAuthorizationRoute
  FormsPermitIntakeRoute: typeof FormsPermitIntakeRoute
  FormsSubcontractorIntakeRoute: typeof FormsSubcontractorIntakeRoute
}

const FormsRouteChildren: FormsRouteChildren = {
  FormsPaymentAuthorizationRoute: FormsPaymentAuthorizationRoute,
  FormsPermitIntakeRoute: FormsPermitIntakeRoute,
  FormsSubcontractorIntakeRoute: FormsSubcontractorIntakeRoute,
}

const FormsRouteWithChildren = FormsRoute._addFileChildren(FormsRouteChildren)

interface PortalRouteChildren {
  PortalInspectionsRoute: typeof PortalInspectionsRoute
  PortalNewPermitRoute: typeof PortalNewPermitRoute
  PortalProjectsRoute: typeof PortalProjectsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalInspectionsRoute: PortalInspectionsRoute,
  PortalNewPermitRoute: PortalNewPermitRoute,
  PortalProjectsRoute: PortalProjectsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AskVictoriaRoute: AskVictoriaRoute,
  BuildingDeptLoginsRoute: BuildingDeptLoginsRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FeeCalculatorRoute: FeeCalculatorRoute,
  FormsRoute: FormsRouteWithChildren,
  InsuranceRoute: InsuranceRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  LpoaSigningRoute: LpoaSigningRoute,
  MessagesRoute: MessagesRoute,
  MyPermitsRoute: MyPermitsRoute,
  PortalRoute: PortalRouteWithChildren,
  ProcessRoute: ProcessRoute,
  ProfileRoute: ProfileRoute,
  ProjectGuidesRoute: ProjectGuidesRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
