-- Task 10 municipality_logins is paused.
--
-- The existing `gc_portal_logins` table and `src/lib/portal-logins.functions.ts` already
-- cover this use case. This migration is intentionally a no-op until the owner confirms
-- whether to repurpose, merge, or remove this schema.
